### ISSUE TITLE
Adding new board Cinwrite S3 with IT8951 epaper controller

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/IT8951-esp32-epub-reader#1]
Thanks to @Jason
Let's use this Issue to communicate forward!

Next blocker for this:  Either separate the IT8951 from epdiy since @atomic14 used this library as a base to keep the framebuffer. But EPDiy in this version does not support ESP32S3.

My wish will be to erradicate epdiy completely for IT8951 displays and instead use Lovyan GFX that supports IT8951. But that would be a complete revamp of the engine. And a cowboy should go slow and easy peasy to avoid falling of the horse :horse_racing:

**Comment by Jason2866** [comment]
From schematics i see you use a S3 module which exists in different variants :-)
The exact naming on the module is relevant to know flash / psram size and type.
<img width="734" alt="Bildschirmfoto 2022-11-26 um 11 44 49" src="https://user-images.githubusercontent.com/24528715/204084815-46ed2926-8fc4-49fc-9ee5-195f7a3833fa.png">
You should not use a module without PSRAM

**Comment by Jason2866** [comment]
@martinberlin Fixed. PR #2
It was a wrong pio setup

**Comment by Jason2866** [comment]
It seems adopting the epdiy lib for S3 is possible without too much work.

**Comment by martinberlin** [comment]
Thanks Jason, will merge it after testing!
Yes in fact I have a fork that supports S3 in EPDiy:
https://github.com/martinberlin/epdiy-rotation/tree/lilygos3

Forgot to say the S3 model is N4R2 has 2 MB external RAM.

**Comment by Jason2866** [comment]
The boards.json for the S3 fits 100%. If you can eliminate the compile errors it should at least boot ;-)

**Comment by martinberlin** [comment]
Thanks a lot Jason!
Merging this as soon as possible. Big ePub reader starts to take shape!

**Comment by Jason2866** [comment]
The Usb-Serial converter chip is a option not to mount on the PCB.
Programming via inbuilt Usb Serial / Jtag works without any problems.
Just some changes in boards.json to use CDC (to see serial console)

**Comment by martinberlin** [comment]
Here a [small video demo](https://twitter.com/martinfasani/status/1596627706887618560)

**Comment by martinberlin** [comment]
Please send me your address to martin AT cale.es
Would like to send you a small present, one of [my SPI boards](https://www.tindie.com/products/fasani/tinypico-spi-hat-with-rtc-for-good-display-epaper/), that has RTC and it's nice to make a clock or anything with a SPI epaper from GoodDisplay.

**Comment by Jason2866** [comment]
Do you have a source for the 2.7 ePaper?
https://www.buy-lcd.com/products/27inch-264x176-spi-e-ink-display
Sold out :-(  Other sellers i found a very expensive.

**Comment by martinberlin** [comment]
IT8951 version is almost there!
https://twitter.com/martinfasani/status/1597256098301374465

Thanks for your help, all seems to work nicely building in Platformio now, your small SPI adapter present is on the way to you

**Comment by Jason2866** [comment]
Nice to see already a demo running!
