### ISSUE TITLE
SD card issue on S3

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/IT8951-esp32-epub-reader#6]
Still could not make it work with the SD card.

Maybe also bad hardware since I got the cheapest microSD from Aliexpress...

IO PINS: 

     ; setup the pins for the SDCard
     -DSD_CARD_PIN_NUM_CLK=GPIO_NUM_18
     -DSD_CARD_PIN_NUM_MOSI=GPIO_NUM_16
     -DSD_CARD_PIN_NUM_MISO=GPIO_NUM_14
     -DSD_CARD_PIN_NUM_CS=GPIO_NUM_9

Error in Serial

```
I (1899) SDC: Initializing SD card
I (1899) gpio: GPIO[9]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (1909) sdspi_transaction: cmd=52, R1 response: command not supported
I (1959) sdspi_transaction: cmd=5, R1 response: command not supported
E (2959) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
E (2959) vfs_fat_sdmmc: sdmmc_card_init failed (0x107).
I (2959) gpio: GPIO[9]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
E (2969) SDC: Failed to initialize the card (ESP_ERR_TIMEOUT). Make sure SD card lines have pull-up resistors in place.
```

**Comment by Jason2866** [comment]
Looks like a hardware problem. SD cards works fine on my S3 cam board (where it is factory mounted).

**Comment by martinberlin** [comment]
Yes I tried it externally and also does not work. Probably cheap hardware with some level shifters prepared only for 5 V like arduino boards…
Looking around later for a new microSD. Thanks!

**Comment by martinberlin** [comment]
The issue was that 32 GB does not work. With a 16 GB SD works correctly
